name: Build IPA

on:
  push:
    branches: [ main ]  # 当推送到 main 分支时触发
  pull_request:
    branches: [ main ]  # 当创建针对 main 分支的 PR 时触发
  workflow_dispatch:    # 保留手动触发选项

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
        
    - name: Build App
      run: |
        # 列出可用的 scheme
        xcodebuild -list
        
        # 使用详细输出模式构建
        xcodebuild -scheme "Zomigle (Release)" \
          -configuration Release \
          -sdk iphoneos \
          -derivedDataPath build \
          DEVELOPMENT_TEAM="" \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGNING_ALLOWED=NO
        
        # 检查构建输出目录
        ls -la build/Build/Products/Release-iphoneos/
        
    - name: Create Payload Directory
      run: |
        mkdir -p Payload
        cp -r build/Build/Products/Release-iphoneos/Zomigle.app Payload/
        
    - name: Create TIPA
      run: |
        zip -r Zomigle.tipa Payload/
        
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Zomigle
        path: Zomigle.tipa 
        
