name: Build IPA

on:
  push:
    branches: [ main ]  # 当推送到 main 分支时触发
  pull_request:
    branches: [ main ]  # 当创建针对 main 分支的 PR 时触发
  workflow_dispatch:    # 保留手动触发选项

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
        
    - name: Build App
      run: |
        xcodebuild -scheme "Zomigle (Release)" -configuration Release
        
    - name: Create Payload Directory
      run: |
        mkdir Payload
        cp -r build/Release-iphoneos/Zomigle.app Payload/
        
    - name: Create TIPA
      run: |
        zip -r Zomigle.tipa Payload/
        
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: Zomigle
        path: Zomigle.tipa 