name: Build IPA

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
    
    - name: Add Source Files
      run: |
        # 创建 trollstore_helper.m
        cat > Zomigle/trollstore_helper.m << 'EOL'
        #import <Foundation/Foundation.h>
        #import <dlfcn.h>
        #import <unistd.h>
        #import <sys/stat.h>

        BOOL isTrollStore(void) {
            NSString *bundlePath = [[NSBundle mainBundle] bundlePath];
            return [[NSFileManager defaultManager] fileExistsAtPath:[bundlePath stringByAppendingPathComponent:@".trollstore_installed"]];
        }

        void setTrollStoreEnvironment(void) {
            NSString *bundlePath = [[NSBundle mainBundle] bundlePath];
            [[NSFileManager defaultManager] createFileAtPath:[bundlePath stringByAppendingPathComponent:@".trollstore_installed"] contents:nil attributes:nil];
            chmod("/var/mobile/Library/Preferences", 0755);
            chmod("/var/mobile/Library/Preferences/com.apple.NanoRegistry.plist", 0644);
        }
        EOL
        
        # 将文件添加到项目中
        /usr/libexec/PlistBuddy -c "Add :objects:NEW_ID:isa string PBXFileReference" Zomigle.xcodeproj/project.pbxproj
        /usr/libexec/PlistBuddy -c "Add :objects:NEW_ID:path string trollstore_helper.m" Zomigle.xcodeproj/project.pbxproj
        /usr/libexec/PlistBuddy -c "Add :objects:NEW_ID:sourceTree string '<group>'" Zomigle.xcodeproj/project.pbxproj
        
        # 添加到编译源文件中
        /usr/libexec/PlistBuddy -c "Add :objects:BUILD_ID:isa string PBXBuildFile" Zomigle.xcodeproj/project.pbxproj
        /usr/libexec/PlistBuddy -c "Add :objects:BUILD_ID:fileRef string NEW_ID" Zomigle.xcodeproj/project.pbxproj
    
    - name: Build Archive
      run: |
        xcodebuild archive \
          -project Zomigle.xcodeproj \
          -scheme "Zomigle (Release)" \
          -configuration Release \
          -archivePath build/Zomigle.xcarchive \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGNING_ALLOWED=NO \
          OTHER_CFLAGS="-DPLATFORM_APPLICATION=1" \
          OTHER_SWIFT_FLAGS="-DPLATFORM_APPLICATION" \
          PLATFORM_ENTITLEMENTS=YES \
          VALIDATE_PRODUCT=NO \
          COPY_PHASE_STRIP=NO \
          ENABLE_BITCODE=NO \
          DEVELOPMENT_TEAM="" \
          PRODUCT_BUNDLE_IDENTIFIER="xyz.hhls.laosijijumo"
          
    - name: Create IPA
      run: |
        cd build
        mkdir Payload
        cp -r Zomigle.xcarchive/Products/Applications/Zomigle.app Payload/
        touch "Payload/Zomigle.app/.trollstore_installed"
        zip -r Zomigle.ipa Payload
        rm -rf Payload
        
    - name: Upload IPA
      uses: actions/upload-artifact@v4
      with:
        name: Zomigle
        path: build/Zomigle.ipa 