name: Build IPA

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
    
    - name: Add Source Files
      run: |
        # 创建 trollstore_helper.m
        cat > Zomigle/trollstore_helper.m << 'EOL'
        #import <Foundation/Foundation.h>
        #import <dlfcn.h>
        #import <unistd.h>
        #import <sys/stat.h>

        BOOL isTrollStore(void) {
            NSString *bundlePath = [[NSBundle mainBundle] bundlePath];
            return [[NSFileManager defaultManager] fileExistsAtPath:[bundlePath stringByAppendingPathComponent:@".trollstore_installed"]];
        }

        void setTrollStoreEnvironment(void) {
            NSString *bundlePath = [[NSBundle mainBundle] bundlePath];
            [[NSFileManager defaultManager] createFileAtPath:[bundlePath stringByAppendingPathComponent:@".trollstore_installed"] contents:nil attributes:nil];
            chmod("/var/mobile/Library/Preferences", 0755);
            chmod("/var/mobile/Library/Preferences/com.apple.NanoRegistry.plist", 0644);
        }
        EOL
        
        # 生成 UUID
        HELPER_UUID=$(uuidgen | tr "[:upper:]" "[:lower:]")
        BUILD_UUID=$(uuidgen | tr "[:upper:]" "[:lower:]")
        
        # 备份原始文件
        cp Zomigle.xcodeproj/project.pbxproj Zomigle.xcodeproj/project.pbxproj.bak
        
        # 创建临时文件
        cat > pbxproj_changes.txt << EOF
        /* Begin PBXFileReference section */
        		$HELPER_UUID /* trollstore_helper.m */ = {isa = PBXFileReference; fileEncoding = 4; lastKnownFileType = sourcecode.c.objc; path = trollstore_helper.m; sourceTree = "<group>"; };
        /* End PBXFileReference section */
        
        /* Begin PBXBuildFile section */
        		$BUILD_UUID /* trollstore_helper.m in Sources */ = {isa = PBXBuildFile; fileRef = $HELPER_UUID /* trollstore_helper.m */; };
        /* End PBXBuildFile section */
        EOF
        
        # 使用 plutil 合并更改
        plutil -insert "objects.$HELPER_UUID" -json '{"isa":"PBXFileReference","fileEncoding":4,"lastKnownFileType":"sourcecode.c.objc","path":"trollstore_helper.m","sourceTree":"<group>"}' Zomigle.xcodeproj/project.pbxproj
        plutil -insert "objects.$BUILD_UUID" -json '{"isa":"PBXBuildFile","fileRef":"'$HELPER_UUID'"}' Zomigle.xcodeproj/project.pbxproj
        
        # 添加到 Zomigle 组
        GROUP_UUID=$(plutil -extract objects.D0D353BD2B92E01300555898.children xml1 -o - Zomigle.xcodeproj/project.pbxproj | grep -A1 "array" | tail -1 | sed 's/.*>\(.*\)<.*/\1/')
        plutil -insert "objects.D0D353BD2B92E01300555898.children.-1" -string "$HELPER_UUID" Zomigle.xcodeproj/project.pbxproj
        
        # 添加到编译阶段
        BUILD_PHASE_UUID=$(plutil -extract objects.D0D353B72B92E01300555898.files xml1 -o - Zomigle.xcodeproj/project.pbxproj | grep -A1 "array" | tail -1 | sed 's/.*>\(.*\)<.*/\1/')
        plutil -insert "objects.D0D353B72B92E01300555898.files.-1" -string "$BUILD_UUID" Zomigle.xcodeproj/project.pbxproj
        
        # 验证文件格式
        if ! plutil -lint Zomigle.xcodeproj/project.pbxproj; then
          echo "Error: Invalid project file format"
          cp Zomigle.xcodeproj/project.pbxproj.bak Zomigle.xcodeproj/project.pbxproj
          exit 1
        fi

    - name: Build Archive
      run: |
        xcodebuild archive \
          -project Zomigle.xcodeproj \
          -scheme "Zomigle (Release)" \
          -configuration Release \
          -archivePath build/Zomigle.xcarchive \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGNING_ALLOWED=NO \
          OTHER_CFLAGS="-DPLATFORM_APPLICATION=1" \
          OTHER_SWIFT_FLAGS="-DPLATFORM_APPLICATION" \
          PLATFORM_ENTITLEMENTS=YES \
          VALIDATE_PRODUCT=NO \
          COPY_PHASE_STRIP=NO \
          ENABLE_BITCODE=NO \
          DEVELOPMENT_TEAM="" \
          PRODUCT_BUNDLE_IDENTIFIER="xyz.hhls.laosijijumo"
          
    - name: Create IPA
      run: |
        cd build
        mkdir Payload
        cp -r Zomigle.xcarchive/Products/Applications/Zomigle.app Payload/
        touch "Payload/Zomigle.app/.trollstore_installed"
        zip -r Zomigle.ipa Payload
        rm -rf Payload
        
    - name: Upload IPA
      uses: actions/upload-artifact@v4
      with:
        name: Zomigle
        path: build/Zomigle.ipa 