name: Build IPA

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
    
    - name: Build Archive
      run: |
        xcodebuild archive \
          -project Zomigle.xcodeproj \
          -scheme "Zomigle (Release)" \
          -configuration Release \
          -archivePath build/Zomigle.xcarchive \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGNING_ALLOWED=NO \
          OTHER_CFLAGS="-DPLATFORM_APPLICATION=1" \
          OTHER_SWIFT_FLAGS="-DPLATFORM_APPLICATION" \
          PLATFORM_ENTITLEMENTS=YES \
          VALIDATE_PRODUCT=NO \
          COPY_PHASE_STRIP=NO \
          ENABLE_BITCODE=NO \
          DEVELOPMENT_TEAM="" \
          PRODUCT_BUNDLE_IDENTIFIER="xyz.hhls.laosijijumo"
          
    - name: Create IPA
      run: |
        cd build
        mkdir Payload
        cp -r Zomigle.xcarchive/Products/Applications/Zomigle.app Payload/
        zip -r Zomigle.ipa Payload
        rm -rf Payload
        
    - name: Upload IPA
      uses: actions/upload-artifact@v4
      with:
        name: Zomigle
        path: build/Zomigle.ipa 