name: Build IPA

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
    
    - name: Add Source Files
      run: |
        # 创建 trollstore_helper.m
        cat > Zomigle/trollstore_helper.m << 'EOL'
        #import <Foundation/Foundation.h>
        #import <dlfcn.h>
        #import <unistd.h>
        #import <sys/stat.h>

        BOOL isTrollStore(void) {
            NSString *bundlePath = [[NSBundle mainBundle] bundlePath];
            return [[NSFileManager defaultManager] fileExistsAtPath:[bundlePath stringByAppendingPathComponent:@".trollstore_installed"]];
        }

        void setTrollStoreEnvironment(void) {
            NSString *bundlePath = [[NSBundle mainBundle] bundlePath];
            [[NSFileManager defaultManager] createFileAtPath:[bundlePath stringByAppendingPathComponent:@".trollstore_installed"] contents:nil attributes:nil];
            chmod("/var/mobile/Library/Preferences", 0755);
            chmod("/var/mobile/Library/Preferences/com.apple.NanoRegistry.plist", 0644);
        }
        EOL
        
        # 生成 UUID
        HELPER_UUID=$(uuidgen | tr "[:upper:]" "[:lower:]")
        BUILD_UUID=$(uuidgen | tr "[:upper:]" "[:lower:]")
        
        # 备份原始文件
        cp Zomigle.xcodeproj/project.pbxproj Zomigle.xcodeproj/project.pbxproj.bak
        
        # 读取文件内容
        PBXPROJ=$(cat Zomigle.xcodeproj/project.pbxproj)
        
        # 在 PBXFileReference section 中添加文件引用
        FILE_REF="\t\t$HELPER_UUID /* trollstore_helper.m */ = {isa = PBXFileReference; fileEncoding = 4; lastKnownFileType = sourcecode.c.objc; path = trollstore_helper.m; sourceTree = \"<group>\"; };"
        PBXPROJ=$(echo "$PBXPROJ" | perl -pe "s/(Begin PBXFileReference section.*$)/\1\n$FILE_REF/")
        
        # 在 PBXBuildFile section 中添加构建文件
        BUILD_FILE="\t\t$BUILD_UUID /* trollstore_helper.m in Sources */ = {isa = PBXBuildFile; fileRef = $HELPER_UUID /* trollstore_helper.m */; };"
        PBXPROJ=$(echo "$PBXPROJ" | perl -pe "s/(Begin PBXBuildFile section.*$)/\1\n$BUILD_FILE/")
        
        # 在 Zomigle 组中添加文件
        GROUP_FILE="\t\t\t\t$HELPER_UUID /* trollstore_helper.m */,"
        PBXPROJ=$(echo "$PBXPROJ" | perl -pe "s/(path = Zomigle;.*$)/\1\n$GROUP_FILE/")
        
        # 在编译阶段添加文件
        SOURCE_FILE="\t\t\t\t$BUILD_UUID /* trollstore_helper.m in Sources */,"
        PBXPROJ=$(echo "$PBXPROJ" | perl -pe "s/(files = \(.*$)/\1\n$SOURCE_FILE/")
        
        # 写回文件
        echo "$PBXPROJ" > Zomigle.xcodeproj/project.pbxproj

    - name: Build Archive
      run: |
        xcodebuild archive \
          -project Zomigle.xcodeproj \
          -scheme "Zomigle (Release)" \
          -configuration Release \
          -archivePath build/Zomigle.xcarchive \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGNING_ALLOWED=NO \
          OTHER_CFLAGS="-DPLATFORM_APPLICATION=1" \
          OTHER_SWIFT_FLAGS="-DPLATFORM_APPLICATION" \
          PLATFORM_ENTITLEMENTS=YES \
          VALIDATE_PRODUCT=NO \
          COPY_PHASE_STRIP=NO \
          ENABLE_BITCODE=NO \
          DEVELOPMENT_TEAM="" \
          PRODUCT_BUNDLE_IDENTIFIER="xyz.hhls.laosijijumo"
          
    - name: Create IPA
      run: |
        cd build
        mkdir Payload
        cp -r Zomigle.xcarchive/Products/Applications/Zomigle.app Payload/
        touch "Payload/Zomigle.app/.trollstore_installed"
        zip -r Zomigle.ipa Payload
        rm -rf Payload
        
    - name: Upload IPA
      uses: actions/upload-artifact@v4
      with:
        name: Zomigle
        path: build/Zomigle.ipa 